server:
  port: 9021

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.112.27.58/lzjd?connectTimeout=5000&socketTimeout=60000&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: biz123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:/sqlmap/mybatis/mysql/mapper/*.xml
    type-aliases-package: com.lzjd.mis.graduate.api.domain

logging:
    level:
      com.lzjd.mis.graduate.api.dao.mapper: debug

Spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
